# Generated by Django 4.1.3 on 2023-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(default='e78162cdc74d499f9af49212f894d6bf', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('article_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('banner', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('article_tag_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_articletag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('commentary_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_commentary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('department_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'api_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('feature_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('image_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('order_id', models.CharField(default='adf8f783436145f2b727cafbcf719ff4', editable=False, max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('order_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'api_orderproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'api_paymentmethod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('stock', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'api_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('product_subcategory_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_productsubcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('role_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'api_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('specification_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_specification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('state_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'api_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('subcategory_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('tag_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'api_tag',
                'managed': False,
            },
        ),
    ]
