name: "deploy"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
      - name: Install npm packages
        run: npm install
        working-directory: ./frontend
      - name: Config build
        run: npm ci
        working-directory: ./frontend
      - name: Build project
        run: npm run build
        working-directory: ./frontend
      - name: Create .static
        run: touch .static
        working-directory: ./frontend/dist
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@tulipannstore.com:web"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
