name: "deploy"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enter to folder
        run: cd ${{github.action_path}}/frontend
        shell: bash
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
      - name: Install npm packages
        run: npm install
      - name: Config build
        run: npm ci
      - name: Build project
        run: npm build
      - name: Create .static
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./dist/.static"
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@tulipannstore.com:web"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
