name: App Deploy

on:
  #workflow_run:
  #workflows: ["App Build"]
  #types:
  #- completed
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          ref: web

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: "--force -vvv"
          git_remote_url: "ssh://dokku@tulipannstore.com:22/web"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
